swagger: "2.0"
info:
  description: "A simple web API that returns the weather for a provided city."
  version: "1.0.0"
  title: "Yara Works API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "yusuf@spacemango.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
tags:
- name: "weather"
  description: "Everything about the weather"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /api/v2/weather/{location}:
    get:
      tags:
      - "weather"
      summary: "Find the weather in a city"
      description: "Returns the weather in a city"
      operationId: "getCityWeather"
      produces:
      - "application/json"
      parameters:
      - name: "location"
        in: "path"
        description: "the city to fetch the weather for"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/WeatherResult"
        "500":
          description: "Unable to fetch weather"
          schema:
            $ref: "#/definitions/ErrorResult"
definitions:
  WeatherResult:
    type: "object"
    properties:
      main:
        type: "string"
        example: "Drizzle"
        description: "the short description of the weather"
      description:
        type: "string"
        example: "light intensity drizzle"
        description: "a longer description of the weather"
      temperature:
        type: "integer"
        format: "int64"
        example: "287.99"
        description: "the temperate in kelvin"
      feelsLike:
        type: "integer"
        format: "int64"
        example: "286.57"
        description: "the feels like temperate in kelvin"
      pressure:
        type: "integer"
        format: "int64"
        example: "1021"
        description: "the atmospheric pressure in hPa"
      humidity:
        type: "integer"
        format: "int64"
        example: "40"
        description: "the percentage humidity"
  ErrorResult:
    type: "object"
    properties:
      msg:
        type: "string"
        example: "Unable to fetch weather"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"